dependencies {
    //  implementation("org.springframework.boot:spring-boot-starter-liquibase")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")
}

bootBuildImage {
    imageName = "abondar/bookstore-book-service"
}